languages:
  JavaScript: true
engines:
  coffeelint:
    enabled: true
  csslint:
    enabled: true
exclude_paths:
- ".git"
- ".tmp"
- "bower_components"
- "coverage"
- "node_modules"
- "LICENSE"
- "README.md"
- "Procfile"
- "nodemon.json"
- "bower.json"
- "cody/assets/*"
- "cody/public/*"
