language: node_js
node_js:
- '0.10'
before_install:
- npm install -g codeclimate-test-reporter
after_script:
- ./node_modules/.bin/istanbul cover -x "**/vendor/**" ./node_modules/.bin/_mocha --
- codeclimate < coverage/lcov.info
services:
- mongodb
env:
- NODE_ENV=test CODECLIMATE_REPO_TOKEN=c5b2952432c62c390850c87a2c41ed62a0fee517b80650fc9a955d7683b8ac9a
deploy:
  provider: heroku
  api_key:
    secure: LnXAnDbfp7dYsPN1UKBpx2jOADE51ZFTJBIK+quPKDvqDyAXIkVT9Fjh9eaEjnPxP+Rm6L0jStcb2oy7+l8B+34FA6pAaWSHYo++q1l6FDwiXLpp14CLG0kjOC4GZ5Q3eo/Onj/jL5uhs3Frz7tZ45Naz2ybMK6pybqLw7N3hxI=
  app: codycf
  on:
    repo: CodeFrogITUG/cody
