language: node_js
node_js:
- '0.12'
#before_install:
#- npm install -g codeclimate-test-reporter
#script:
#- npm run coverage
#after_script:
#- codeclimate < coverage/lcov.info
services:
- mongodb
env:
- NODE_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: Oc19y64NhfOGOFNPXI+ZxL0GeQc3P7HtWQL8C8HJAH874Os2HQRRLdIpIO/D0QloG7n3ATOfvxV7gi0CAqcOUCIfXkiQNCQvzvj9+18o5OgpRSCmnxZaUQ/+1ff7CWvhxB65/l3fSjkL86Jc3+J6st2E5Vnhy/Kg1f9BB6yQHJI=
  app: cody
  on:
    repo: CodeFrogHub/cody
